/*R*/
export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
/*R*/
export const LOAD_SERVICE_REQUEST = 'LOAD_SERVICE_REQUEST';
export const LOAD_SERVICE_FAILURE = 'LOAD_SERVICE_FAILURE';
export const LOAD_SERVICE_SUCCESS = 'LOAD_SERVICE_SUCCESS';
/*U*/
export const SAVE_SERVICE_REQUEST = 'SAVE_SERVICE_REQUEST';
export const SAVE_SERVICE_FAILURE = 'SAVE_SERVICE_FAILURE';
export const SAVE_SERVICE_SUCCESS = 'SAVE_SERVICE_SUCCESS';
/*D*/
export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';


